version: '1.0'

services:
  mongodb:
    image: mongo:latest
    container_name: practica1_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/mnt/data        
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

networks:
  practica1_network:
    driver: bridge

volumes:
  mongodb_data:
