version: '1.0'

services:
  mongodb:
    image: mongo:latest
    container_name: practica1_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  python-init:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_init
    depends_on:
      - mongodb
    volumes:
      - ./python:/mnt/python
      - ./data:/mnt/data
    restart: "no"

  app-web:
    build:
      context: ./dashboard-tips
      dockerfile: Dockerfile
    container_name: app_web
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./dashboard-tips:/app
      - ./data:/mnt/data
    restart: always

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
